# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

def dev_pods
  pod 'SwiftLint', '= 0.43.1', configurations: ['Debug']
  pod 'SwiftGen', '= 6.4.0', configurations: ['Debug']
end

def core_pods
  pod 'RxSwift', '= 5.1.1'
  pod 'RxRelay', '= 5.1.1'
end

def ui_pods
  pod 'SnapKit', '= 5.0.1'
  pod 'RxCocoa', '= 5.1.1'
  pod 'RxDataSources', '= 4.0.1'
end

target 'Dancer' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # 用户操作日志
  pod 'KillBug'
  # 加速库
  pod 'SpeedySwift'
  # 网路库
  pod 'CTNet', :path => 'Dev-Pods/CTNet'

  
  dev_pods
  core_pods
  ui_pods
  
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
      config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
    end
  end
end
